### ISSUE TITLE
Should use Vinyl objects instead of reading from the file system

### ISSUE THREAD

**Issue by rasenplanscher** [HerringtonDarkholme/gulp-progeny#11]
I've just been trying this out and was surprised to find that this actually reads every file on its own instead of using the Vinyl objects from the stream. Is there a specific reason for that? After all, you can expect to get the contents from the stream and do not need to repeat the read process, do you?

**Comment by HerringtonDarkholme** [comment]
The problem is I don't have handle to Vinyl objects after parsing dependencies in files. Using readSync is more generic

**Comment by rasenplanscher** [comment]
In `module.exports` of `index.js` you resolve the path and forward it until it reaches `parseDeps` in `parse.js` – which is where you have your call to `fs.readFileSync`. You could just as easily forward the Vinyl handle instead of the path and read the contents from that.

> Using readSync is more generic

That is correct. It's also unnecessary since this is a gulp plugin and gulp –and, by extension, your code– relies on Vinyl objects. Additionally you introduce a problem that gulp wants to get around in the first place. One of gulp's main advantages over grunt is that it uses stream and thereby *drastically reduces* file-system access, which is one of the main bottle-necks of grunt. You may want to read up on this point here: https://github.com/substack/stream-handbook#why-you-should-use-streams

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome

**Comment by rasenplanscher** [comment]
For anybody interested, check this out: https://www.npmjs.com/package/gulp-inheritance
