### ISSUE TITLE
Error when deleting cache[child] in pushFileRecursive

### ISSUE THREAD

**Issue by stevenremot** [HerringtonDarkholme/gulp-progeny#12]
Hi!

I get this error at a moment I cannot define, when using progeny in my Less watchers:

```js
[...]/node_modules/gulp-progeny/dest/index.js:57
      results.push(delete cache[child]);
                                ^
RangeError: Maximum call stack size exceeded
```

I looked a bit to the code, and it seems the variable `child` is not defined anywhere in the code. Maybe you meant `childPath` ?

**Comment by HerringtonDarkholme** [comment]
Thanks for report! 

fixed in https://github.com/HerringtonDarkholme/gulp-progeny/commit/460dfacb26f7cef2dee6b58bf424e2ada69625bf

**Comment by stevenremot** [comment]
Wow, that was fast! Thanks for the fix.
