### ISSUE TITLE
Doesn't handle glob imports (Stylus)

### ISSUE THREAD

**Issue by straker** [HerringtonDarkholme/gulp-progeny#15]
[Stylus supports file globbing](http://stylus-lang.com/docs/import.html#file-globbing) in its import/require statements. However, gulp-progeny does not detect these dependencies.

Running gulp-progeny with an import statement such as `@import 'helpers/*'` (with debug turned on), outputs:

```
DEP file.styl
    |  NO-DEP
```

**Comment by straker** [comment]
it appears that I just needed to set rootPath correctly and now globs work. Sorry about that.

**Comment by HerringtonDarkholme** [comment]
You're welcome.

The problem is that you're importing an absolute path `/helpers/*`. So you need to specify the `rootPath`.
