### ISSUE TITLE
Support for progeny's altPaths

### ISSUE THREAD

**Issue by diagramatics** [HerringtonDarkholme/gulp-progeny#17]
Based on es128/progeny, I don't think we have support for `altPaths` yet unfortunately.

Which brings me to another question: is it a possibility if we just use es128/progeny for the parser, use their API then fit in Gulp's structure instead?

**Comment by HerringtonDarkholme** [comment]
What's the use case of `altPath`? I don't quite get the meaning of it.

>  is it a possibility if we just use es128/progeny for the parser, use their API then fit in Gulp's structure instead?

It is quite a large change that I cannot afford. Pull request is welcome nevertheless.

**Comment by diagramatics** [comment]
It serves as an additional path for dependency resolution. For example if I add `node_modules` for resolving third party dependencies, I can do `normalize/normalize.css` and it'll check in that directory as well.

I was tinkering with just outright replacing the `parse.js` import with `progeny` and it seems to work fine with my LESS codebase apart from the 3 test errors.

**Comment by diagramatics** [comment]
Out of the issue topic, I've managed to iron out 2/3 test errors by fixing them upstream. The only thing left would be the "deep watch" and commit https://github.com/HerringtonDarkholme/gulp-progeny/commit/7f98123fc5ab8602313eb6a10776090ed4e086cf on the `shallowDep` option. Can I get more detail about it and why it was there to see if it's something I can fix upstream or if it's actually unnecessary?

**Comment by HerringtonDarkholme** [comment]
If I recollect correctly, if one dep is changed, it should update all deps recursively. 
progeny skip this recursion by only checking the direct child dependencies. And recursively send files to gulp stream.

The shallowDep option is actually a transition, I think. Because I wonder whether it would break compatibility.
