### ISSUE TITLE
Reverse Progeny

### ISSUE THREAD

**Issue by epitaphmike** [HerringtonDarkholme/gulp-progeny#2]
Any thoughts on a reverse method? 
When a child is updated, the parent(s) are recompiled?

**Comment by amio** [comment]
Seems the words `parent` & `child` cause some confusion,
consider choosing some other term better fits the meaning?

**Comment by mikeya** [comment]
Pogeny doesn't seem to work with more than 2 level nested of parents, so if there were grandparents, the grandchildren don't get compiled.

**Comment by HerringtonDarkholme** [comment]
@mikeya Please provide example files. I have not encounter any problem in my project so far

**Comment by seansfkelley** [comment]
I just accidentally reproed this while checking out the fix for #5. This seems to happen when the grandparent is added after the task starts; so starting with the same repro described in #5:

```
### Start repro same was #5 starts.

Starting 'test'...
gulp-debug: child.test
DEP child.test
    |--parent.test
gulp-debug: parent.test
DEP parent.test
    |  NO-DEP
gulp-debug: 2 items
Finished 'test' after 30 ms
Starting 'watch'...
Finished 'watch' after 11 ms

### Add empty grandparent.test file.

Starting 'test'...
gulp-debug: grandparent.test
DEP grandparent.test
    |  NO-DEP
gulp-debug: 1 items
Finished 'test' after 8.75 ms

### Add 'import grandparent.test' line in parent.test.

Starting 'test'...
gulp-debug: parent.test
DEP parent.test
    |--grandparent.test
gulp-debug: child.test
gulp-debug: 2 items
Finished 'test' after 86 ms

### Touch grandparent file (e.g. add a newline) -- does not recompile child.test.

Starting 'test'...
gulp-debug: grandparent.test
DEP grandparent.test
    |  NO-DEP
gulp-debug: parent.test
gulp-debug: 2 items
Finished 'test' after 4.98 ms
```

Where `grandparent.test` is just an empty file. If you start the task while all three levels of files exist, it works as expected:

```
### Start task with all three files in place.

Starting 'test'...
gulp-debug: child.test
DEP child.test
    |--parent.test
    |--grandparent.test
gulp-debug: grandparent.test
DEP grandparent.test
    |  NO-DEP
gulp-debug: parent.test
DEP parent.test
    |--grandparent.test
gulp-debug: 3 items
Finished 'test' after 43 ms
Starting 'watch'...
Finished 'watch' after 12 ms

### Modify grandparent.test -- everything is recompiled, as expected.

Starting 'test'...
gulp-debug: grandparent.test
DEP grandparent.test
    |  NO-DEP
gulp-debug: child.test
gulp-debug: parent.test
gulp-debug: 3 items
Finished 'test' after 9.49 ms
```

**Comment by HerringtonDarkholme** [comment]
@seansfkelley Thanks for reporting! I'm investigating this. For now you will have to manually edit child to update the dependency tree.

**Comment by HerringtonDarkholme** [comment]
@seansfkelley fixed in https://github.com/HerringtonDarkholme/gulp-progeny/commit/7f98123fc5ab8602313eb6a10776090ed4e086cf

**Comment by salex772** [comment]
I think the definitions of parents and children are confusing here. The most root level must be called a parent.
