### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by mitchhentges** [HerringtonDarkholme/gulp-progeny#20]
Currently, the project description is "Makes gulp blazing fast".
I feel that it's a missed opportunity to tie into Drumpf culture and be "Make Gulp Fast Again"?

I've made a small image to inspire this change.
![america](https://cloud.githubusercontent.com/assets/7784737/16401860/b64f8072-3c9c-11e6-8710-dc0df91bed22.jpeg)

**Comment by HerringtonDarkholme** [comment]
Your humor is welcome :)

If you have decent logo image I'm happy to add it in the readme

**Comment by mitchhentges** [comment]
Hmm, not sure about a logo, but the GitHub description maybe :wink:

**Comment by HerringtonDarkholme** [comment]
Hilarious, LOL

![mgfg](https://cloud.githubusercontent.com/assets/2883231/16402559/b731b766-3d1f-11e6-9026-cb1e1d4a9278.png)

**Comment by mitchhentges** [comment]
That's beautiful. It's actually polished, too, and not made with MS-Paint (probably). :+1:
