### ISSUE TITLE
Usage with gulp-pug and includes

### ISSUE THREAD

**Issue by chrisjansky** [HerringtonDarkholme/gulp-progeny#23]
I've spent countless hours trying to set up some sort of an incremental build system with gulp-changed, gulp-jade-inheritance etc., but always scrapped it in the end as it. just. did. not. work. This plugin seems very promising – I've managed to plug it into my workflow and make it work, thanks!

Can you please provide an example on how to use it to compile .pug containing includes/mixins? The classic scenario of compiling a page if you change the linked file.

```
index.pug
  - mixins/
    - _helper.pug
```

index.pug containing `include mixins/_helper.pug`.

I want `index.pug` to compile to `index.html` regardless if I edit it directly or change something in `_helper.pug`. Naturally I don't want `_helper.pug` to result in `_helper.html`.

**Comment by HerringtonDarkholme** [comment]
My suggestion is to use `src('./**/*.pug')` to source all the pug files and pipe them to progeny,
then, use [gulp-filter](https://www.npmjs.com/package/gulp-filter) to filter out what you don't want to produce result.

```ts
gulp.src('./**/*.pug')
  .pipe(cached('pug'))
  .pipe(progeny(pugConfig))
  .pipe(filter(/^[^_]/)) // not start with underscore _
  .pipe(pug())
  .dest()
```

**Comment by chrisjansky** [comment]
Thanks for the quick response. I am being a little dumb here, but can you please clarify the `.pipe(progeny(pugConfig))` part? I looked into `progeny` docs and can't find clear explanation on what it should contain.

`.pipe(progeny({extension: 'pug'}))` does not seem to work.

Also, I changed the `gulp-filter` part to `.pipe(filter('**/!(_)*.pug'))` as `.pipe(filter(/^[^_]/))` returned `pattern should be a string, array, or function`.

Thanks for your time!

**Comment by HerringtonDarkholme** [comment]
Sorry, I haven't used gulp for long. The above code is just my best memory of the config I wrote two years ago.

I think you can re-read gulp-filter's doc and progeny's documentation. If possible, asking on stack-overflow is also good.

**Comment by es128** [comment]
Built-in pug support was added in progeny 0.11.0. This module will need a version bump in package.json to use it. 

Semver doesn't automatically apply minor patches on 0.x versions, the bump to 1.0.0 is probably long overdue.

**Comment by HerringtonDarkholme** [comment]
Version bumped. Pug file should be handled without config.
