### ISSUE TITLE
Error on included Pug partials

### ISSUE THREAD

**Issue by Grawl** [HerringtonDarkholme/gulp-progeny#24]
Everything is ok on root files but an error occurred on included partials:

```
2017-05-02 15:16 gulp[2466] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```

<details>
<summary><code>gulpfile</code></summary>

```js
…
const $ = gulpLoadPlugins()
const bs = browsersync.create()
gulp.task('views', () => {
	bs.notify('Compiling HTML…', 999999)
    return gulp.src(['app/*.pug', 'app/views/**/*.pug'])
        .pipe($.if(global.isWatching, $.cached('pug')))
	.pipe($.progeny())
        .pipe($.pug({ pretty: true }))
        .pipe(gulp.dest('.tmp'))
		.pipe(bs.reload({ stream: true }))
})
…
gulp.task('serve', () => {
	global.isWatching = true
	runSequence(['clean'], ['views', 'styles', 'scripts'], () => {
		…
		gulp.watch(
			[
				'app/**/*.pug',
				'app/includes/**/*',
			],
			['views']
		)
		…
	})
})
```

</details>

The same as with `gulp-pug-inheritance` https://github.com/pure180/gulp-pug-inheritance/issues/5

Maybe something wrong with my `gilpfile`?

**Comment by HerringtonDarkholme** [comment]
I don't see anything related to gulp progeny, but I suspect this error is related to nodejs' `watch` implementation. Maybe it is not plugin's fault.

**Comment by Grawl** [comment]
Oh sorry my bad.

the problem is into Node itself: https://github.com/nodejs/node/issues/854
