### ISSUE TITLE
gulp-stylus -> gulp-progeny fails with progeny attempting to parse non-existant .css files

### ISSUE THREAD

**Issue by mogelbrod** [HerringtonDarkholme/gulp-progeny#7]
After reinstalling the entire node_module dependency tree in an app (and most likely installing new versions of everything) gulp-progeny started throwing `ENOENT` (file not found) errors.

The issue seems to be that gulp-progeny [attempts to parse](https://github.com/HerringtonDarkholme/gulp-progeny/blob/master/src/parse.coffee#L110) the path that is emitted by gulp-stylus (with `.styl` [replaced by](https://github.com/stevelacy/gulp-stylus/blob/master/index.js#L35) `.css`) instead of the original file path. The following code throws the error for me:

```js
gulp.src(['styles/**/*.styl'], {cwd: 'styles'})
  .pipe(gulpProgeny())
  .pipe(gulp.dest(destDir));
```

Temporarily switching the file extensions back to `.styl` using `gulp-rename` seems to work however:
```js
gulp.src(['styles/**/*.styl'], {cwd: 'styles'})
  .pipe(gulpRename({ extname: '.styl' }))
  .pipe(gulpProgeny())
  .pipe(gulpRename({ extname: '.css' }))
  .pipe(gulp.dest(destDir));
```

Gulp versions:
```
gulp@3.9.0
gulp-cached@1.1.0
gulp-progeny@0.1.1
-- gulp-util@2.2.20
gulp-rename@1.2.2
gulp-stylus@2.0.6
gulp-util@3.0.6
```

**Comment by HerringtonDarkholme** [comment]
Can you provide example configuration? I'm sorry I cannot understand your problem.
I use gulp-progeny and gulp-stylus every day and nothing seems go wrong.

**Comment by mogelbrod** [comment]
Sure!

```bash
mkdir test
cd test
mkdir styles
```

**package.json:**
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gulp": "^3.9.0",
    "gulp-cached": "^1.1.0",
    "gulp-progeny": "^0.1.2",
    "gulp-rename": "^1.2.2",
    "gulp-stylus": "^2.0.6",
    "livescript": "^1.4.0"
  }
}
```

**gulpfile.ls:** (LiveScript, hope that's okay)
```ls
require! <[ gulp gulp-stylus gulp-progeny gulp-rename ]>

gulp.task \failing, ->
  gulp.src ['**/*.styl'], cwd: \styles
    .pipe gulp-stylus!
    .pipe gulp-progeny!
    .pipe gulp.dest \build

gulp.task \working, ->
  gulp.src ['**/*.styl'], cwd: \styles
    .pipe gulp-stylus!
    .pipe gulp-rename extname: \.styl
    .pipe gulp-progeny!
    .pipe gulp-rename extname: \.css
    .pipe gulp.dest \build

gulp.task \default, <[ failing ]>
```

**styles/index.styl:**
```stylus
body
  background: green
```

**Run the test cases:**
```bash
npm install
gulp failing # Should throw "Error: no writecb in Transform class"
gulp working # Should work
```

**Comment by HerringtonDarkholme** [comment]
Oops, I think progeny should go before stylus. Just like the [#example](https://github.com/HerringtonDarkholme/gulp-progeny#usage).

Internally progeny checks whether dependency files exists, but if the file is provided by gulp, it skip checking.

**Comment by mogelbrod** [comment]
Haha, what a dumb mistake by me :D
Thanks for pointing it out, and for the quick replies!
