### ISSUE TITLE
Consider dependency parser as separate components

### ISSUE THREAD

**Issue by amio** [HerringtonDarkholme/gulp-progeny#8]
Leave it up to user to determine how dependencies are parsed,
maybe used like:
```javascript
var stylDepParser = function(text){/*...*/}
gulp.src('*.styl')
  .pipe(progeny({
    depParser: stylDepParser
  }))
```
then the core should be more simple, and with no [limitation](https://github.com/HerringtonDarkholme/gulp-progeny#limitation).

**Comment by HerringtonDarkholme** [comment]
If user has mighty power to implement dependency parsers, then they probably should choose Broccoli, though.

I don't think progeny is a powerful plugin, neither it will be. It just provides quick and dirty way towards faster compilation. Minimal interface and easy-dumb regex are chosen for this.

**Comment by amio** [comment]
You can provide the parser too, just separate them into standalone components, making gulp-progeny more simple, even an elegent way, not just a quick and dirty way.

**Comment by HerringtonDarkholme** [comment]
Fork is welcome ;)

**Comment by amio** [comment]
Alright, thanks for your patient.
（混蛋你就懒死吧）
