### ISSUE TITLE
Sync reading files

### ISSUE THREAD

**Issue by unlight** [HerringtonDarkholme/gulp-progeny#9]
I've just started looking code.
I spotted that a lot of synchronous code for reading/checking files `fs.readFileSync`, `fs.existsSync`.
Is it necessary? Can you give short explanation?

**Comment by HerringtonDarkholme** [comment]
These operations are blocking in nature. And building process does not have concurrency in most case. Node's single thread model precludes multi-core building, indeed.
 So sync is clearly better.

**Comment by es128** [comment]
@HerringtonDarkholme Not that I have a stake here, and am only aware of this module since it is influenced by my [progeny](https://github.com/es128/progeny). But I strongly disagree with the perspective you just expressed. There's a significant perf difference using sync vs async methods with the file system. And there is obvious i/o concurrency in this use case when crawling through a dependency graph.

You'd be much better off actually using progeny under this than the reimplementation you ended up with.

**Comment by HerringtonDarkholme** [comment]
@es128 I respect your authority, and I don't want to argue with a brilliant developer solely based on my own opinion. 
Feel free to leave this reimplementation I ended up with. But if you are very interested. Here is a little `test.js` I jotted down.

```js
var fs = require('fs')
var startSync = Date.now()
for (var i = 0; i < 10000; i++) {
  fs.readFileSync(__dirname + '/test.js')
}
console.log('sync read: ' + (Date.now() - startSync))

var startAsync = Date.now()
var i = 0
function readFile() {
  fs.readFile(__dirname + '/test.js', function() {
    if (++i >= 10000) {
      console.log('async read: ' + (Date.now() - startAsync))
    }
  })
}
for (var j = 0; j < 10000; j++) {
  readFile()
}
```

**Comment by es128** [comment]
Not trying to be argumentative, just discussing what appears to be a misconception on your part. The points you made in response to the question are wrong, and this module would almost certainly benefit from refactoring to async.

You're completely misleading yourself with this test. Using async doesn't make the file get read faster, it unblocks the node process.

**Comment by HerringtonDarkholme** [comment]
Benchmark, please. 

I don't think refactoring to async will be a big help. Bottleneck of building is compiling, not reading file. It's compiling blocks readFileSync, not vice-versa.

And async incurs context-switching overhead, closure overhead, and I'm not sure concurrent file reading can compensate these overhead. Even it does, I don't think it worth several callback recursion in code.

**Comment by es128** [comment]
> Bottleneck of building is compiling, not reading file

That's pretty funny coming from someone working within the gulp ecosystem.

**Comment by HerringtonDarkholme** [comment]
Please avoid [ad hominem](https://en.wikipedia.org/wiki/Ad_hominem). I cannot understand your point.

**Comment by es128** [comment]
It wasn't ad hominem. The point is that you're effectively arguing that grunt should be just as performant as gulp.

**Comment by HerringtonDarkholme** [comment]
I don't see the rhetorical technique to be valid, though.

Again, please provide factual evidence to support gulp is more performant than grunt. And tell how it relates to this issue.

I have stated my opinion towards synchronous reading, and provides factual benchmark(regardless of its validity).

**Comment by es128** [comment]
It's ok, I won't be spending any more time on this. I am genuinely sorry if any of my comments came across as hurtful, that wasn't my intention - I was just reacting to your initial response which came across to me as very far off base. I believe your perception of fs sync methods is incorrect, but it's up to you to be receptive to that feedback and to look further into it. It's your module, you're free to run it however you like.

**Comment by unlight** [comment]
Agree.
Using *-sync is a bad practice. It is not gulpy way.
Consider to replace filter(fs.exists) by [`filter.asyc`](https://github.com/parshap/node-stream-filter) or similar, using map from [event-stream](https://github.com/dominictarr/event-stream#map-asyncfunction) and so on.

**Comment by HerringtonDarkholme** [comment]
Pull request is welcom
